CREATE TABLE llx_dk_backup_evidence (
    rowid BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    evidence_uuid VARCHAR(36) NOT NULL,
    deployment_id VARCHAR(128) NOT NULL,
    backup_type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    started_at DATETIME NOT NULL,
    completed_at DATETIME NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    provider_registration VARCHAR(128) NOT NULL,
    country CHAR(2) NOT NULL,
    region VARCHAR(128) NOT NULL,
    object_reference VARCHAR(500) NOT NULL,
    receipt_sha256 CHAR(64) NOT NULL,
    byte_size BIGINT NOT NULL,
    retention_until DATE NOT NULL,
    immutable_until DATE NOT NULL,
    signature_verified TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uk_dk_backup_evidence_uuid (evidence_uuid),
    KEY idx_dk_backup_deployment_type (entity, deployment_id, backup_type, completed_at),
    KEY idx_dk_backup_retention (entity, retention_until, immutable_until)
) ENGINE=InnoDB;
