CREATE TABLE llx_dk_saft_import (
    rowid BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    import_uuid VARCHAR(36) NOT NULL,
    source_hash CHAR(64) NOT NULL,
    audit_file_version VARCHAR(16) NOT NULL,
    source_company_registration VARCHAR(64) NULL,
    source_company_name VARCHAR(255) NOT NULL,
    default_currency_code VARCHAR(3) NOT NULL,
    standard_account_name VARCHAR(128) NULL,
    standard_account_version VARCHAR(32) NULL,
    selection_start_date DATE NULL,
    selection_end_date DATE NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'staged',
    transaction_count INTEGER NOT NULL,
    line_count INTEGER NOT NULL,
    total_debit DECIMAL(24,8) NOT NULL DEFAULT 0,
    total_credit DECIMAL(24,8) NOT NULL DEFAULT 0,
    fk_user_author BIGINT NOT NULL,
    date_creation DATETIME NOT NULL,
    date_applied DATETIME NULL,
    UNIQUE KEY uk_dk_saft_import_uuid (import_uuid),
    UNIQUE KEY uk_dk_saft_import_source (entity, source_hash),
    KEY idx_dk_saft_import_status (entity, status)
) ENGINE=InnoDB;
