CREATE TABLE llx_dk_einvoice_application_response (
    rowid BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER NOT NULL DEFAULT 1,
    response_uuid VARCHAR(36) NOT NULL,
    delivery_rowid BIGINT NOT NULL,
    channel VARCHAR(32) NOT NULL,
    provider_message_id VARCHAR(255) NOT NULL,
    message_key CHAR(64) NOT NULL,
    sender_endpoint_scheme VARCHAR(32) NOT NULL,
    sender_endpoint_id VARCHAR(128) NOT NULL,
    response_id VARCHAR(255) NOT NULL,
    response_document_uuid VARCHAR(36) NOT NULL,
    issue_date DATE NOT NULL,
    response_code VARCHAR(32) NOT NULL,
    description TEXT NULL,
    referenced_document_id VARCHAR(255) NOT NULL,
    referenced_document_uuid VARCHAR(36) NOT NULL,
    referenced_document_type VARCHAR(32) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    byte_size BIGINT NOT NULL,
    schema_hash CHAR(64) NOT NULL,
    schematron_result_hash CHAR(64) NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    evidence_json LONGTEXT NOT NULL,
    fk_user_author BIGINT NOT NULL DEFAULT 0,
    received_at DATETIME NOT NULL,
    UNIQUE KEY uk_dk_einvoice_response_uuid (response_uuid),
    UNIQUE KEY uk_dk_einvoice_response_message (entity, message_key),
    KEY idx_dk_einvoice_response_delivery (entity, delivery_rowid, rowid)
) ENGINE=InnoDB;
